#!/usr/bin/env bash
deployall=(
"ljapi"
"ljapp"
"ljims"
"ljcms"
"ljwap"
"ljweb"
"ljsearch"
"ljlive"
"ljpush"
"lj-im"
"lj-rss"
"lj-website"
)

listString="";
for  ((i=0; i<${#deployall[*]}; i++))
do
	listString="[${i}]:${deployall[$i]}";
	echo $listString;
done	

while true
do
    read -p "请输入你需要上线的deployment的编号：" NO
	deployment=${deployall[$NO]}
	testLog=test.log
	if [  ${deployment} ]; then
		#echo "select:${deployment}"
		imageStr=$(kubectl --kubeconfig $KUBECONFIG_JDEV get deploy ${deployment} -o jsonpath='{..image}')
		echo "DEV:${imageStr}"
		echo "DEV:${imageStr}" >> $testLog
		imageStr=$(kubectl --kubeconfig $KUBECONFIG_HW_TEST get deploy ${deployment} -o jsonpath='{..image}')
		echo "TEST:${imageStr}"
		echo "TEST:${imageStr}" >> $testLog
		read -p "请输入版本号：" SV
		dt="$(date "+%Y-%m-%d %H:%M:%S") update ${deployment}:${SV}"
		echo $dt
		echo $dt >> $testLog
		kubectl --kubeconfig $KUBECONFIG_HW_TEST  set image deployment/$deployment $deployment=swr.cn-east-2.myhuaweicloud.com/riskflow/$deployment:$SV
		#sleep 3
		kubectl --kubeconfig $KUBECONFIG_HW_TEST  get pod -l app=$deployment
		echo '' >> $testLog
		echo 'next'
	else
		echo "select error "
		exit
	fi
done

