#!/usr/bin/env bash
deployall=(
"cailianpress-admin"
"cailianpress-admin-web"
"cailianpress-api"
"cls-web"
"in-app-views"
"cailianpress-cron"
"cailianpress-featured-api"
"cailianpress-vod"
"cailianpress-payment-v2"
"cailianpress-search"
"cailianpress-openapi"
"core-restful"
"core-service"
"cls-es"
"cailianpress-statics"
"cailianpress-wap"
"dpns-controller"
"dpns-register"
"go-mysql-elasticsearch"
"h5quotes"
"stib-cailianpress-web"
"stib-dpns-controller"
"stib-in-app-views"
"stib-wap"
"cailianpress-credits-mall"
"cailianpress-rss"
"cls-im"
"cls-hw-controller"
"cls-ios-controller"
"cls-jg-controller"
"cls-xm-controller"
"cls-push-getway"
"cls-order"
"cls-sync"
"eoe"
"eoecms"
"cls-ad"
)

listString="";
for  ((i=0; i<${#deployall[*]}; i++))
do
	listString="[${i}]:${deployall[$i]}";
	echo $listString;
done	

while true
do
    read -p "请输入你需要上线的deployment的编号：" NO
	deployment=${deployall[$NO]}
	testLog=test.log
	if [  ${deployment} ]; then
		#echo "select:${deployment}"
		imageStr=$(kubectl --kubeconfig $KUBECONFIG_DEV get deploy ${deployment} -o jsonpath='{..image}')
		echo "DEV:${imageStr}"
		echo "DEV:${imageStr}" >> $testLog
		imageStr=$(kubectl --kubeconfig $KUBECONFIG_TEST get deploy ${deployment} -o jsonpath='{..image}')
		echo "TEST:${imageStr}"
		echo "TEST:${imageStr}" >> $testLog
		read -p "请输入版本号：" SV
		dt="$(date "+%Y-%m-%d %H:%M:%S") update ${deployment}:${SV}"
		echo $dt
		echo $dt >> $testLog
		kubectl --kubeconfig $KUBECONFIG_TEST  set image deployment/$deployment $deployment=swr.cn-east-2.myhuaweicloud.com/yb7/$deployment:$SV
		#sleep 3
		kubectl --kubeconfig $KUBECONFIG_TEST  get pod -l app=$deployment
		echo '' >> $testLog
		echo 'next'
	else
		echo "select error "
		exit
	fi
done

