#!/usr/bin/env bash
deployall=(
"ad-service"
"apns-producer"
"apns-producer-push"
"article-audit"
"article-audit-example"
"blockchain-demo"
"cailianpress-admin"
"cailianpress-admin-web"
"cailianpress-api"
"cailianpress-credits-mall"
"cailianpress-cron"
"cailianpress-featured-api"
"cailianpress-openapi"
"cailianpress-payment"
"cailianpress-payment-v2"
"cailianpress-pc-click"
"cailianpress-search"
"cailianpress-statics"
"cailianpress-vod"
"cailianpress-wap"
"cailianpress-web"
"cls-admin-web3"
"cls-app-email"
"cls-elasticsearch"
"cls-pro-admin"
"cls-pro-api"
"cls-pro-opensearch"
"cls-red-diamond-admin"
"cls-red-diamond-admin-web"
"cls-red-diamond-api"
"cls-red-diamond-api-enovy"
"cls-red-diamond-cron"
"cls-red-diamond-elasticsearch"
"cls-red-diamond-payment"
"clspro-core-service"
"clspro-dpns-controller"
"clspro-dpns-register"
"clspro-in-app-views"
"core-restful"
"core-service"
"deviceledger-api"
"dpns-controller"
"dpns-controller-dev"
"dpns-register"
"go-mysql-elasticsearch"
"h5quotes"
"in-app-views"
"ivr"
"opt-api"
"opt-web"
"sms-service"
"speedup-content-delivery"
"stib-cailianpress-web"
"stib-dpns-controller"
"stib-in-app-views"
)
 
for  value in  ${deployall[@]} ;do
 re="swr.cn-east-2.myhuaweicloud.com/yb7/([^:]+):([^ ]+)"
 imageStr=$(kubectl --kubeconfig $KUBECONFIG_TEST get deploy $value -o jsonpath='{..image}')
 echo "$value test current version"
 if [[ $imageStr =~ $re ]]; then echo ${BASH_REMATCH[2]}; fi


  re="swr.cn-east-2.myhuaweicloud.com/yb7/([^:]+):([^ ]+)"
  imageStr=$(kubectl --kubeconfig $KUBECONFIG_PROD get deploy $value -o jsonpath='{..image}')
  echo "$value online current version"
  if [[ $imageStr =~ $re ]]; then echo ${BASH_REMATCH[2]}; fi
 
done